### ISSUE TITLE
Error breaking up again

### ISSUE THREAD

**Issue by simon1967** [pH7Software/pH7-Social-Dating-CMS#667]
@Undefined-Variables I now have this happening it run for 3 hours then even if i dissable cache and clear them it is the same . If you have chance to have a look I would be grateful after your last help .
So you enter login info press login and this is the problem

/index.php/module/action/param1/static/PFBC/js/jquery/rss/static/css/js/jquery/smoothness/templates/themes/datelove/img/icon/xml/sitemap/user/xml/rss/legal/user/account/index

Thanks Simon

**Comment by Undefined-Variables** [comment]
I already know Simon I looked a while ago I am looking into it as we speak... We are on the right track and we will get to the bottom of it.

**Comment by simon1967** [comment]
Oh I owe you big time it was perfect for 3 hours

Simon

**Comment by Undefined-Variables** [comment]
Yes I know I have been having a look every now and then. I was just starting to think about calling it a night and thought id have one last look... I am starting to feel tired mate. I have been in front of these monitors since 8am, thats 13 long hours. If I can't solve it in the next half hour, we will turn cache off and I will return in the morning with fresh eyes :)

**Comment by simon1967** [comment]
Well i owe you lots cache is already disabled and it is making no
differenceeven after i clear it. We will leave it at that for now. Have
some sleep of course, I am so grateful simon

**Comment by Undefined-Variables** [comment]
Found a typo    

<meta itemprop="description" content="WThe Best Online Social Swinging Service to meet people and keep in touch with your friends" />

**Comment by simon1967** [comment]
Just to say I had to disable data base cache and Html cache to get it
running again.
Thanks
Simon

**Comment by simon1967** [comment]
I do not know how you do this so quick your skill set is amazing

**Comment by Undefined-Variables** [comment]
Tools are a big help... Burp allows me manipulate requests and modify requests to see the impact they have and a good beautifier is essential when looking at output :)

**Comment by simon1967** [comment]
Just to say we are nor on the site as simon that is someone else I am on as
steve n sally

**Comment by simon1967** [comment]
I have a new desktop coming this week I am going to kit it out with all the
things i need like Burp etc to help me grow

**Comment by Undefined-Variables** [comment]
Can you set up a temp user for me to use on your server for me to use? It will be x100 easier if I can ssh to the box cos the way I am doing this is like working backwards... I'm looking for a clue to point me in the right direction... I need IP, username and password. not here though on pm me on your site.

**Comment by simon1967** [comment]
Are you still on the site

**Comment by Undefined-Variables** [comment]
Yeah status is offline that is all

**Comment by simon1967** [comment]
Message me on the site please steve n sally

**Comment by simon1967** [comment]
I can not find you

**Comment by Undefined-Variables** [comment]
07376224032

Text me it, sites going nuts again

**Comment by simon1967** [comment]
ok

**Comment by Undefined-Variables** [comment]
port? 22

**Comment by simon1967** [comment]
Sorry ? port 22 all info has been text I hope

**Comment by simon1967** [comment]
Everything i never thought of at this point

**Comment by simon1967** [comment]
Your dam amazing to me . You now have my email add

**Comment by Undefined-Variables** [comment]
LOL i ask for a ssh user to login with not your contol panel don't worry I will do it. Just give me some time I will fix this once and for all!

**Comment by simon1967** [comment]
Do you need any more info for access and you have my email now if you need
me and my phone number

Simon with thanks

**Comment by simon1967** [comment]
I think you need some sleep , remember it can wait . I am so grateful and
will talk to you at some point

Simon

**Comment by Undefined-Variables** [comment]
No im in your control panel and creating a ssh key pair... Life is simple like this... I do everything from linux terminal, this is luxurious.

**Comment by simon1967** [comment]
We need to meet i mean that

**Comment by simon1967** [comment]
Hope your ok
Simon

**Comment by Undefined-Variables** [comment]
Yeah sorry I had to run out to get tobacco. Putty was not playing ball so thought I'd take 5mins... Just going to smoke a fag and I will be back.

**Comment by simon1967** [comment]
Do you need sleep

**Comment by simon1967** [comment]
Email private

**Comment by Undefined-Variables** [comment]
No just drank a Monster so not yet!

**Comment by simon1967** [comment]
Ok Thanks just wanted to check
Simon

**Comment by Undefined-Variables** [comment]
Right I am going at 11.30 I will continue in the morning.  I need some time so go and have a coffee and watch the news or something I will message at 11.30 and update you.

**Comment by simon1967** [comment]
Ok I am going now thanks so much for your help I will see your message when
it comes Thanks once again

Simon

**Comment by simon1967** [comment]
Take care thanks

**Comment by Undefined-Variables** [comment]
I know for sure 100 million percent the issue is being caused by Ajax. I have definitive proof. The mission now is the solution is to remove Ajax's functionally in a few areas. 

Luckily for me I spent about 3 months designing a theme for this software so I am more than confident doing so. This will take me a few hours so I am going to bed now and will begin the procedure first thing! This will totally fix the problem.

Ajax is best left as a option you can switch off! In these areas this is not currently the case.

**Comment by Undefined-Variables** [comment]
Oh and I have changed the setup of your server so it is now correct. You had a load of php extensions you do not need and will cause you problems down the road. Same with some key settings, please don't alter anything unless you fully understand the implications and reduction in security having such things active bring! I will write a few notes so you know what they do.

**Comment by simon1967** [comment]
Amazing please write the notes if you get chance. Also just to say a big
thanks. I am working today and will not get home till around 7 pm .
Thanks so much amd speak soon
Simon

**Comment by simon1967** [comment]
The only thing I could find this morning was when you browse people other
then that it worked well I thank you so much for what you have done so far
amazing

**Comment by Undefined-Variables** [comment]
Morning... Yeah the basic functions of the site are now working properly, I don't know if you would have noticed but the execution time of the working parts are 1/3 of what they were before I reconfigured a few things. This is just the tip of the iceberg. I spent a long time running requests and capturing the data on a number of browsers and then analysing the results. 

For an example you had php-ext's enabled for all manor of things the software does not use. Like multiple database options and ext's for protocol's like SOAP (used to pass messages using the HTTP protocol) and just about everything with SQL in the name. All these just add to your servers workload and they are not doing anything. All the small things add up and before you know it the server has no resources to do the things it needs to. 

Also the hosting company gives you a set number of allowed requests per hour, day and month, you have 10,000 per month you are over 5,600 already and you have 16 users. This is why having a working and efficient cache is important. When the cache works one request will be made and the page is copied so requests made for the same information are served from the cached page taken earlier. 

You have already registered for HTML5Chat using your email address? I need the password for the account you made. I will have the site completely set up by the end of today and I don't do half jobs with anything. I am only going to do this all for you one time so you need to really think about things before you do them. If you are not sure research first!

**Comment by simon1967** [comment]
Wow amazing I will take everything on board you are saying and learn. I
will come back to you txt message with chat info thanks so much Simon

**Comment by Undefined-Variables** [comment]
Just doing a good deed :)

**Comment by simon1967** [comment]
More than that I will be phoning you after believe me

**Comment by simon1967** [comment]
Just checking in from work hope you're ok

**Comment by simon1967** [comment]
Hi there just wondering if you are ok today

**Comment by polynamaude** [comment]
Hi guys ! With such a title and each other hosting a social dating site then I can only say we have a perfect match !

**Comment by simon1967** [comment]
Hi are you okPolyna-Maude R.-summerside He has been such a help and
insperation I am learning so much from him, He has been so helpful to which
I am grateful. Lots of late nights and early mornings before work. But I
have stuck with it and love the learning curve.
Thanks
Simon
Polyna-Maude R.-Summerside

**Comment by Undefined-Variables** [comment]
@simon1967 Yes I'm all good sorry sleeping took longer than planned! Back on the case now....

Hey @polynamaude Nice to see you :) We have an issue with Ajax. We are creating massive URLs still.

**Comment by simon1967** [comment]
I will leave you with it in peace. I have sent you email too.
Thanks so much

**Comment by Undefined-Variables** [comment]
@simon1967 I had to sort a few things out in real life but I have some free time again now so going to get this done for you.

**Comment by simon1967** [comment]
Wow can I as I keep say I am so grateful your amazing, I have spent till 2
am reading about Ajax . Then i fell asleep , I am at work shortly but will
keep checking emails.
Simon

**Comment by polynamaude** [comment]
@Undefined-Variables Maybe I wasn't clear enough....
Do you really think such a long running issue has any use for other to see ?
I think you shall go onto a social network or open you own slack channel ;-)

**Comment by simon1967** [comment]
Ok Simon

**Comment by Undefined-Variables** [comment]
@polynamaude People only read what that choose to read. No body is forced :)

@simon1967 All should be working now :)

**Comment by polynamaude** [comment]
@Undefined-Variables There's a thing called being "off-topic" and another one called "search feature". So if someone search something they'll get this long standing useless for other discussion in the feeds they will be digging through.

And just like that, instead of saying to people "My time is precious, I don't want to waste mine with people who just opened a Github account" then maybe you shall look at your own story. May I remember what was your situation less than three months ago ?

I'll be more than happy to look back at some deleted messages....Still getting hacked by Youtube and saying the GCHQ is investigating for you ?

**Comment by Undefined-Variables** [comment]
@polynamaude You would enjoy life so much more if you lightened up a little bit! Everything doesn't have to be so matter of fact. Your comments are so depressing to read :(

**Comment by simon1967** [comment]
Agree here team work makes the dream work watch flight of the geese on
YouTube and learn how to honk

**Comment by polynamaude** [comment]
@Undefined-Variables Great to see that you are back down to your usual "I'm the best and I do as I want in life". Maybe you forgot a bit about where you came from and that it's not because you are able to help one person that you became a master in the trade.

Yes it's always depressing to be put back to earth. But you are using what's called an "open issue" that is meant to be used as a reference that can be searched for when we need help. Not used for conversation about the rain, your hours of sleeps or the time you pass smoking cigarettes.

And I'm not talking about "Having a relevant topic". That would be another story. Did it ever went through your mind that other people than you may have interest in using this knowledge base for what it is meant for ?

Take a deep breath, grow up a bit.

**Comment by polynamaude** [comment]
@simon1967 I tried at once to say it nice. You didn't seem to understand my message when I said "You are both hosting a social dating site". Act this way on another forum and you get banned. You don't seem to have much understanding about the right place for the right subject.

I told you many time that this is not a general support forum for the geese, the goose and the whole computing ecosystem.

When we give smooth hint about going to the right place, then you just ignore them.
And if we make it somewhat clearer then you complains useless comments like "Go on Youtube fly like a penguin".

**Comment by simon1967** [comment]
I have to say that first I am grateful to GitHub but the ethos of the site
is not how you come across. I sadly have read many of your comments as I
followed your first Instructions on read the posts. I found some of your
comments were in helpful to the person asking and the same amount of typing
could have helped them develop new skills. Ok let's all 3 of us stop this
conversation as you said GitHub is not for this.

**Comment by Undefined-Variables** [comment]
If anyone likes the sound of polite friendly support without limits...

https://undefined-variables.com

Support minus the drama...

**Comment by polynamaude** [comment]
@Undefined-Variables Just a hint... You installation is broken. The media don't load properly. Don't want to be a drama queen but it looks better when you run your service good before trying to offer to help others.

Cheer !
![Screenshot from 2019-11-08 03-02-51](https://user-images.githubusercontent.com/21186871/68459869-7a040600-01d4-11ea-82e7-46547ecd2e2d.png)
